### ISSUE TITLE
Startup failed on macOS

### ISSUE THREAD

**Issue by JuanDArdilaG** [anbzerc/Anki-ToDo-addon#3]
I was trying to test it but received an error:

<img width="497" alt="image" src="https://github.com/anbzerc/Anki-ToDo-addon/assets/39010502/f968b8c5-6385-45c6-b30f-645967fd8ce9">

Debug Info:
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

When loading Anki Todo:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/juandardilag/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 29, in <module>
    from ToDoQtWindows import ToDoQtWindows
ModuleNotFoundError: No module named 'ToDoQtWindows'

good job btw

**Comment by JuanDArdilaG** [comment]
Hi @anbzerc. I was trying to do it but not sure how. I tried: `open -W Applications/Anki.app` but no output in terminal. I just can see the log that I included in the description of the issue.

**Comment by anbzerc** [comment]
Hi @JuanDArdilaG , according to https://addon-docs.ankiweb.net/console-output.html , `/Applications/Anki.app/Contents/MacOS/anki` should work

**Comment by JuanDArdilaG** [comment]
Super! This is the output:

```
Anki starting...
Initial setup...
Preparing to run...
2024-05-27 18:27:00,597:INFO:aqt.mediasrv: Serving on http://127.0.0.1:52472
['/Users/juandardilag/Library/Application Support/Anki2/addons21', '/Applications/Anki.app/Contents/MacOS/lib', '/Applications/Anki.app/Contents/MacOS/../Resources']
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/juandardilag/Library/Application Support/Anki2/addons21/1807500231/__init__.py", line 29, in <module>
    from ToDoQtWindows import ToDoQtWindows
ModuleNotFoundError: No module named 'ToDoQtWindows'

Starting main loop...
```

**Comment by anbzerc** [comment]
Could you add `print(sys.path)` just before the `from ToDoQtWindows import ToDoQtWindows` in the `__init__.py` ?
To open the init.py you can go to tools / plugins / open folder then find the plugins folder (the same number as the download folder)

**Comment by JuanDArdilaG** [comment]
Yep. There is the error.
The platform variable, that in my case is "darwin", falls into the if statement:
```
if "win" in platform:
    sys.path.append(path + "\\1807500231\\")
else:
    sys.path.append(path + "/1807500231/")
    print(sys.path)
```
and the log is `'/Users/juandardilag/Library/Application Support/Anki2/addons21\\1807500231\\'`

**Comment by anbzerc** [comment]
Thanks ! It should be fixed and the plugin is updated in ankiweb :) . Could you confirm me that it's working ?

**Comment by JuanDArdilaG** [comment]
Great. It's working now. Thanks to you.
I'm going to try it for a while and if I see, or if someone reports,  something else, I could help you. 🙂

**Comment by JuanDArdilaG** [comment]
Great. It's working now. Thanks to you.
I'm going to try it for a while and if I see, or if someone reports, something else, I could help you. 🙂
